/* Automatically generated by wasm2c */
#ifndef MODULO_ARITMETICO_H_GENERATED_
#define MODULO_ARITMETICO_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Z_moduloZ2Daritmetico_instance_t {
  char dummy_member;
} Z_moduloZ2Daritmetico_instance_t;

void Z_moduloZ2Daritmetico_init_module(void);
void Z_moduloZ2Daritmetico_instantiate(Z_moduloZ2Daritmetico_instance_t*);
void Z_moduloZ2Daritmetico_free(Z_moduloZ2Daritmetico_instance_t*);

/* export: 'soma' */
u32 Z_moduloZ2DaritmeticoZ_soma(Z_moduloZ2Daritmetico_instance_t*, u32, u32);

/* export: 'subtracao' */
u32 Z_moduloZ2DaritmeticoZ_subtracao(Z_moduloZ2Daritmetico_instance_t*, u32, u32);

/* export: 'divisao' */
u32 Z_moduloZ2DaritmeticoZ_divisao(Z_moduloZ2Daritmetico_instance_t*, u32, u32);

/* export: 'multiplicacao' */
u32 Z_moduloZ2DaritmeticoZ_multiplicacao(Z_moduloZ2Daritmetico_instance_t*, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* MODULO_ARITMETICO_H_GENERATED_ */
